baseURL = 'https://piperdeck.github.io/piper-ux-portfolio/'
locale = 'en-us'
title = "Piper Deck"
theme = 'piper'

# [menu]
#  [[menu.main]]
#    identifier = "posts"
#    name = "Posts"
#    url = "/posts"

[markup.goldmark.renderer]
  unsafe = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'